### ISSUE TITLE
Maintaining Halcyon for Lisa

### ISSUE THREAD

**Issue by Amit152505** [halcyonproject/docs#1]
Maintainer Name: Nicolas
Telegram Username: @nicolas1525
Device: Xiaomi 11 Lite NE 5g (Lisa)
Device tree link: https://github.com/Amit152505/device_xiaomi_lisa
Kernel Source Link: https://github.com/Amit152505/kernel_xiaomi_lisa.git
Vendor tree link: https://github.com/Amit152505/vendor_xiaomi_lisa

**Comment by slcee** [comment]
After looking on your tree, we are to tell that we can't accept your application due to lack of contribution and multiple violation of our requirements.

In the meantime, you can fix your source code.

We will always welcome you to the team :D
